navikt/tiltakspenger-saksbehandling-api

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/App.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/InMemorySøkerRepository.kt
app/src/test/kotlin/no/nav/tiltakspenger/vedtak/rivers/SøknadMottakRiverTest.kt

Enn så lenge bruker den bare en InMemorySøkerRepository, men det bør like fullt gjøre det mulig å teste en flyt

Koblet inn SøknadMottakRiver så den faktisk lytter på rapiden.

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTO.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/vilkår/Vilkår.kt

På saksopplysning for introprogrammet står det nå “Bruker mottar ikke introprogrammet“ som ikke blir helt riktig. Denne teksten bør heller være “Bruker deltar ikke på introduksjonsprogrammet“ jfm skissene. Disse tekstene kommer fra faktafeltet i saksopplysningDTO og settes i tp-vedtak.

F Endret flatetittel i vilkår til introduksjonsprogrammet

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/sak/PostgresSakRepo.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/sak/SakRepo.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/utbetaling/UtbetalingServiceImpl.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/sak/Sak.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/sak/TynnSak.kt

Lagt til SakDetaljer som et interface som representerer Sak uten underliggende lister, og TynnSak som er en klasse som implementerer SakDetaljer. Sak implementerer også SakDetaljer, men Sak bruker TynnSak vha delegation i implementasjonen. Dette er ikke egentlig synlig utenfor Sak, TynnSak er gjemt bort vha delegation og en factory metode i companion object.
SakRepo::hentKunSak(sakId: SakId): Sak? 
med emptyLister i Sak er endret til å være 
SakRepo::hentSakDetaljer(sakId: SakId): SakDetaljer?
Denne brukes pt bare fra UtbetalingServiceImpl

Lagt til SakDetaljer

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/behandling/PostgresBehandlingRepo.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTO.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/behandling/BehandlingServiceImpl.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/vedtak/VedtakServiceImpl.kt
common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/BehandlingMother.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/BehandlingIverksatt.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/BehandlingStatus.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/BehandlingTilBeslutter.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/BehandlingVilkårsvurdert.kt
domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/Søknadsbehandling.kt

Dette er kanskje kontroversielt, men jeg synes koden ble enklere å både lese, skrive og forstå av å fjerne det innerste laget med sealed classes i Behandling. Vi hadde ulike klasser per status (innvilget, avslag, manuell), men det var bare statusen som varierte. Det meste annet var likt. Jeg forstår ikke at dette er en god bruk av sealed classes, så jeg flata ut hierarkiet litt.
Diffen er vanskelig å lese, så jeg anbefaler å pulle ned branchen.
NB. Jeg baserte meg på forrige PR da jeg gjorde dette, hvor jeg skrev om litt rundt Saksopplysning. Så de endringene er også med her. Sorry, men det gjorde alt så mye lettere..

Fjernet innerste sealed class laget i behandling

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTO.kt
app/src/test/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTOTest.kt

Skrevet enhetstester til det meste av funksjonene som er i `SammenstillingForBehandlingDTO`
* Fjernet `private` fra `hentUtfallForVilkår` for å få skrevet test av implementasjonen dens.
* Tar gjerne kommentarer på hvordan vi evt best legger inn en tilstand-property på de ulike behandling-interfacene (se todo-kommentar her: https://github.com/navikt/tiltakspenger-vedtak/compare/test-av-sammenstilling-for-behandling-dto?expand=1#diff-19a1a69406e283e5e043f9383c3d63596f0ccf8da219eadbcfef9d8107cc370fR168)

D Skrevet enhetstester til SammenstillingForBehandlingDTO

---

common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/BehandlingMother.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/BehandlingOpprettet.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/BehandlingTilBeslutter.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/BehandlingVilkårsvurdert.kt

Vi har innføre en spolTilbake-funksjon i BehandlingTilBeslutter og BehandlingVilkårsvurdert, som returnerer BehandlingOpprettet. Funksjoner som leggTilsøknad og leggTilSaksopplysning kaller så den, og deretter leggTilSøknad/leggTilSaksopplysning på BehandlingOpprettet, i stedet for å duplisere koden i egen klasse.

Fjernet en del duplisert kode 

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/Configuration.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/pdfgen/BrevFørstegangsvedtakInnvilgelseDTO.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/pdfgen/DokumentMeldekortDTO.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/pdfgen/PdfgenHttpClient.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/person/MicrosoftGraphApiClient.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/context/ApplicationContext.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/context/FørstegangsbehandlingContext.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/context/PersonContext.kt
domene/src/main/kotlin/no/nav/tiltakspenger/felles/KunneIkkeHenteNavnForNavIdent.kt
domene/src/main/kotlin/no/nav/tiltakspenger/felles/NavIdentClient.kt
domene/src/main/kotlin/no/nav/tiltakspenger/felles/exceptions/IkkeLoggDenneException.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/ports/GenererMeldekortPdfGateway.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/ports/GenererVedtaksbrevGateway.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/journalføring/JournalførVedtaksbrevService.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/common/TestApplicationContext.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/fakes/clients/GenererFakeMeldekortPdfGateway.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/fakes/clients/GenererFakeVedtaksbrevGateway.kt

La til interfacet `NavIdentClient` som implementeres av `MicrosoftGraphApiClient`.
Denne klienten henter ut saksbehandlers navn via ident fra microsoft graph api.
Den blir initialisert inne i PersonContext (kan eventuelt flyttes til en ny context)
Har lagt inn kallet for både saksbehandler og beslutter når man genererer brev.
Har lagt til ny miljøvariabel for dev og prod:
"MICROSOFT_SCOPE" = "https://graph.microsoft.com"
(lokalt er den bare "localhost")
Har også endret på navngivning i metoder som lå inne fra før:
"hentNavn" -> "hentBrukersNavn"
Synes det er greit å spesifisere at det er brukers navn som hentes siden det nå eksisterer en 'hentSaksbehandlersNavn' i samme scope.

F legg inn en klient som kaller microsoftGraphApi og henter ut saksbehandlers navn.

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/meldekort/MeldeperiodePostgresRepo.kt
app/src/test/kotlin/no/nav/tiltakspenger/vedtak/db/TestDataHelperBehandlingEx.kt
app/src/test/kotlin/no/nav/tiltakspenger/vedtak/repository/meldekort/MeldekortBehandlingRepoImplTest.kt
app/src/test/kotlin/no/nav/tiltakspenger/vedtak/repository/utbetaling/UtbetalingsvedtakRepoImplTest.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldekortBehandling.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/Meldeperiode.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldeperiodeKjede.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldeperiodeKjeder.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/service/IverksettMeldekortService.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/MeldekortMother.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/UtbetalingsvedtakMother.kt

Vi har en bug i produksjon der beslutter ikke får iverksatt meldekort fordi meldeperiodene ikke hentes i sortert rekkefølge.

Sorter meldeperioder

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/meldekort/dto/MeldeperiodeKjedeDTO.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldekortBehandling.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldekortBehandlinger.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/Meldeperiode.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldeperiodeBeregning.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldeperiodeKjede.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/MeldeperiodeKjeder.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/SendMeldekortTilBeslutterKommando.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/service/IverksettMeldekortService.kt
domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/service/SendMeldekortTilBeslutterService.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/sak/Sak.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/behandling/BehandlingServiceImpl.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/sak/SakService.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/sak/SakServiceImpl.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/MeldekortMother.kt

- Lager ny meldeperiode når man iverksetter stans-revurdering.
- Sperrer fra å iverksette meldekortbehandling med utdatert meldeperiode.
- Sperrer fra å sende meldekortbehandling til beslutning med utdatert meldeperiode.
- Dersom det finnes en åpen meldekortbehandling når man iverksetter revurdering, og det genereres en ny meldeperiode som gjør meldeperioden på behandlingen utdatert overskriver vi meldeperioden, fjerner beregningen og setter behandlingen til under behandling

Synkroniser stansvedtak med meldeperiode og meldekort

---

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/jobb/EndretTiltaksdeltakerJobb.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/behandling/BehandlingPostgresRepo.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/behandling/SaksopplysningerDbJson.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/behandling/ValgteTiltaksdeltagelserDbJson.kt
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/dto/SaksopplysningerDTO.kt
app/src/main/resources/db/migration/V46__valgte_tiltaksdeltakelser.sql
app/src/main/resources/db/migration/V47__migrer_valgte_tiltaksdeltakelser.sql
app/src/main/resources/db/migration/V48__migrer_saksopplysninger_tiltaksdeltagelser.sql
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/Behandling.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/saksopplysninger/Saksopplysninger.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/tiltak/ValgteTiltaksdeltakelser.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/vedtak/Vedtaksliste.kt
domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/behandling/OppdaterSaksopplysningerService.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/SakMother.kt
test-common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/SaksopplysningerMother.kt

Støtter at tiltaksdeltakelser på saksopplysninger er en liste, og legger til rette for at vi tar vare på hvilke perioder saksbehandler valgte for gitte titlaksdeltakelser hvis det er flere som overlapper. 
Migrerer også dataene i databasen: 
- tiltaksdeltagelser blir en liste på saksopplysninger
- legger tiltaksdeltakelsen fra saksopplysningene inn som periodisert valgt tiltaksdeltakelse på behandlingen
https://trello.com/c/W9ifbenn/1315-st%C3%B8tte-at-vi-f%C3%A5r-flere-tiltak-fra-arena-komet-n%C3%A5r-vi-s%C3%B8ker-opp-et-fnr

Saksopplysninger liste tiltaksdeltagelser

---

app/build.gradle.kts
app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/datadeling/DatadelingBehandlingJson.kt
domene/build.gradle.kts
test-common/build.gradle.kts

Informasjonen er fjernet fra tiltakspenger-datadeling fordi den ikke var i bruk. 
https://trello.com/c/W9ifbenn/1315-st%C3%B8tte-at-vi-f%C3%A5r-flere-tiltak-fra-arena-komet-n%C3%A5r-vi-s%C3%B8ker-opp-et-fnr

1315 sender ikke lenger informasjon om tiltaket til datadeling

---

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/repository/søknad/SøknadDAO.kt
app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/repository/meldekort/MeldeperiodePostgresRepoTest.kt

Må takle flere søknader for en deltakelse. Bør bli riktig uansett siden vi kun har en sak pr person.

Deltakelse kafka flere soknader

---

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/App.kt

Siden fnr uansett maskeres i vanlig logg er det mye mer praktisk å logge exceptions i vanlig logg, i tillegg til at vi ikke må inn i sikker logg der vi risikerer å se sensitive opplysninger vi ikke har behov for hver gang vi skal sjekke en feilmelding.

logger exceptions i vanlig logg

---

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandling.kt
app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandlinger.kt
app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortbehandlingBegrunnelse.kt
app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/SendMeldekortTilBeslutningKommando.kt
app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/repository/meldekort/MeldekortBehandlingPostgresRepo.kt
app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/routes/meldekort/SendMeldekortTilBeslutterRoute.kt
app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/routes/meldekort/dto/MeldekortBehandlingDTO.kt
app/src/main/resources/db/migration/V57__meldekortbehandling_begrunnelse.sql
app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/MeldekortMother.kt
app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/repository/meldekort/MeldekortBehandlingRepoImplTest.kt
app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/routes/meldekort/SendMeldekortBehandlingTilBeslutterRouteTest.kt
app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/service/SendMeldekortBehandlingTilBeslutterServiceTest.kt

Legger til mulighet for begrunnelse for meldekort for saksbehandler
https://trello.com/c/xKq1PSBo/1398-meldekortbehandling-legg-til-begrunnelsesfelt-som-vises-i-oppsummering-og-til-beslutter

Begrunnelse meldekort

---

app/src/main/resources/db/migration/V59__recreate_replication_slot.sql
app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/db/TestDatabaseManager.kt

https://trello.com/c/QqTI8Drv/1414-n%C3%A5r-vi-oppdaterte-postgres-fra-16-%E2%86%92-17-ble-replication-sloten-til-basen-borte-kort-forklart-er-dette-det-som-gj%C3%B8r-at-bigquery-ka

1414 forsøker å sette opp replication slot på nytt

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/App.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/SakRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/StatistikkSakRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/StatistikkStønadRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/SøknadRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/Configuration.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/IdenthendelseService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/jobb/IdenthendelseJobb.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/kafka/IdenthendelseKafkaProducer.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/repo/IdenthendelseRepository.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/sak/infra/repo/SakPostgresRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/infra/repo/sak/StatistikkSakRepoImpl.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/infra/repo/stønad/StatistikkStønadPostgresRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/infra/repo/PostgresSøknadRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/infra/repo/SøknadDAO.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/SakFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/StatistikkSakFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/StatistikkStønadFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/SøknadFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/IdenthendelseServiceTest.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/jobb/IdenthendelseJobbTest.kt

Hvis det er endring på fnr på en av våre brukere så skriver vi endringen på intern kafkatopic slik at vi får propagert endringen videre ut i verdikjeden vår. Deretter oppdaterer vi i saksbehandling-api-databasen. 
Gjorde også en endring slik at vi ikke lagrer identhendelser i det hele tatt hvis en av endringene vil medføre at vi kan få flere saker pr fnr (sånn koden var ville vi ha lagret den første endringen, og dermed oppdatert i alle appene våre, og det er ikke sikkert at ville vært riktig). 
https://trello.com/c/Ck4Sc5nT/1430-hvis-bruker-som-finnes-i-v%C3%A5rt-system-endrer-fnr-s%C3%A5-skal-vi-oppdatere-alle-steder-der-vi-har-lagret-fnr

Behandle identhendelse

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/infra/route/SøknadDTO.kt

https://trello.com/c/1IB0frWG/1446-n%C3%A5r-bruker-har-flere-tiltak-b%C3%B8r-den-forh%C3%A5ndsutfylte-innvilgelsesperioden-v%C3%A6re-perioden-for-det-tiltaket-man-har-s%C3%B8kt-for

1446 må returnere id for søknadstiltaket for lettere matching i frontend

---

.github/workflows/.test-and-build.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/test-and-build-on-push.yml
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/IverksettBehandlingService.kt

Flytter ferdigstillingen av oppgave til etter vi er ferdig med lagringen slik at hvis ferdigstilling feiler så slipper vi at dataene våre er i usynk, da er det kun ferdigstillingen som mangler.

Ferdigstill rekkefolge

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/route/Routes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandlet.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandlingStatus.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortUnderBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldekortBehandlingPostgresRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldekortBehandlingStatusDb.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/MeldekortRoutes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/OvertaMeldekortBehandlingRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldekortBehandlingStatusDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldeperiodeKjedeStatusDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/setup/MeldekortContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/ports/MeldekortBehandlingRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/overta/KunneIkkeOvertaMeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/overta/OvertaMeldekortBehandlingCommand.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/overta/OvertaMeldekortBehandlingService.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/MeldekortBehandlingFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/OvertaMeldekortBehandlingRouteTest.kt

Saksbehandler skal kunne overta en meldekortbehandling fra en annen saksbehandler. Har også renamet statusen meldekortbehandlingen får når den opprettes så det er tydelig at den da er under behandling (den opprettes av saksbehandler). 
https://trello.com/c/iYXkiirR/1458-en-p%C3%A5startet-manuell-meldekortbehandling-m%C3%A5-kunne-overtas-av-en-annen-saksbehandler

Overta meldekortbehandling

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/route/Routes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/KunneIkkeUnderkjenneMeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletAutomatisk.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletManuelt.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandlingStatus.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortUnderBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldekortBehandlingPostgresRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldekortBehandlingStatusDb.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/MeldekortRoutes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/TaMeldekortBehandlingRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/UnderkjennMeldekortBehandlingRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldekortBehandlingStatusDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldeperiodeKjedeStatusDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/setup/MeldekortContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/ports/MeldekortBehandlingRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/IverksettMeldekortService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/TaMeldekortBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/UnderkjennMeldekortBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/overta/OvertaMeldekortBehandlingService.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/MeldekortBehandlingFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandlingManuellTest.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/OvertaMeldekortBehandlingRouteTest.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/TaMeldekortBehandlingBuilder.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/TaMeldekortBehandlingRouteTest.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/BehandlingMother.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/MeldekortMother.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/routes/RouteBuilder.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/service/OpprettUtbetalingsvedtakServiceTest.kt

Innfører en ny status UNDER_BESLUTNING. Når et meldekort setter til KLAR_TIL_BESLUTNING må beslutter velge å tildele behandlingen til seg selv. Da settes beslutter til den aktuelle beslutteren, og statusen blir UNDER_BESLUTNING. Man kan ikke iverksette fra andre statuser enn UNDER_BESLUTNING. 
Hvis behandlingen er UNDER_BESLUTNING kan også en annen beslutter velge å overta behandlingen. 
https://trello.com/c/iYXkiirR/1458-en-p%C3%A5startet-manuell-meldekortbehandling-m%C3%A5-kunne-overtas-av-en-annen-saksbehandler

Meldekort tildel beslutter

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/setup/MeldekortContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/IverksettMeldekortService.kt

For meldekort som behandles manuelt har vi ikke noen kobling til brukers meldekort på selve meldekortbehandling-objektet. For å se om vi skal ferdigstille en oppgave må vi slå opp i meldekort_bruker-tabellen for å se om det finnes et meldekort med en oppgave knyttet til seg for samme meldeperiode. Hvis det gjør det kan vi ferdigstille den. 
https://trello.com/c/D2IoW0Tx/1472-oppgaven-for-mottatt-meldekort-blir-ikke-ferdigstilt-automatisk

1472 må hente evt oppgave fra brukers meldekort i databasen

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/route/Routes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/KanIkkeLeggeTilbakeMeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletAutomatisk.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletManuelt.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortUnderBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldekortBehandlingPostgresRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/LeggTilbakeMeldekortBehandlingRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/MeldekortRoutes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldekortBehandlingDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/setup/MeldekortContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/ports/MeldekortBehandlingRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/LeggTilbakeMeldekortBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/TaMeldekortBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/Utbetalingsvedtak.kt
src/main/resources/db/migration/V78__meldekortbehandling_saksbehandler_nullable.sql
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/MeldekortBehandlingFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/LeggTilbakeMeldekortBehandlingRouteTest.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/TaMeldekortBehandlingRouteTest.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/MeldekortMother.kt

- Gjør saksbehandler optional på meldekortbehandlingen slik at saksbehandler kan fjerne seg selv
- Saksbehandler må kunne tildele seg selv hvis det ikke er angitt noen saksbehandler
- Saksbehandler og beslutter skal kunne legge tilbake meldekortbehandlingen
https://trello.com/c/gMr9XKsr/1468-legg-tilbake-behandling-saksbehandler-og-beslutter-meldekort-og-s%C3%B8knadsbehandling

Meldekort legg tilbake

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/setup/BehandlingOgVedtakContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/StatistikkSakRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/StatistikkStønadRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/BehandlingServiceImpl.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/IverksettBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/LeggTilbakeBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/SendBehandlingTilBeslutningService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/StartSøknadsbehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/TaBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/overta/OvertaBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/sak/StartRevurderingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/StatistikkContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakMapper.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakRepoImpl.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkStønadDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkStønadMapper.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkStønadPostgresRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkUtbetalingDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/Utbetalingsvedtak.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/LocalApplicationContext.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/common/TestApplicationContext.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/StatistikkSakFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/StatistikkStønadFakeRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/infra/repo/TestDataHelper.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/jobb/IdenthendelseJobbTest.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/PersonhendelseServiceTest.kt

DVH ønsker informasjon om behandlingen av saken, inkludert når saken sendes til beslutter, underkjennes, endrer saksbehandler/beslutter osv. Jeg har lagt til dette, samt innført en ny statistikk-status for sakene som er under beslutning. Vi manglet også statistikk for oppretting av revurdering. 
https://trello.com/c/qQ7idKtU/1078-sende-statistikk-n%C3%A5r-vi-sender-f%C3%B8rstegangsvedtak-til-beslutter

1078 deler alle saksbehandlingsoverganger med statistikk

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/domene/Behandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/route/AvbruttDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/route/Routes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/AvbruttMeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/KanIkkeAvbryteMeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletAutomatisk.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletManuelt.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandlingStatus.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortUnderBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldekortBehandlingPostgresRepo.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldekortBehandlingStatusDb.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/AvbrytMeldekortBehandlingRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/MeldekortRoutes.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldekortBehandlingDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldekortBehandlingStatusDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldeperiodeKjedeStatusDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/setup/MeldekortContext.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/AvbrytMeldekortBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/LeggTilbakeMeldekortBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/TaMeldekortBehandlingService.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/overta/OvertaMeldekortBehandlingService.kt
src/main/resources/db/migration/V82__meldekortbehandling_add_avbrutt.sql
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/AvbrytMeldekortBehandlingRouteTest.kt

Ny status og type for avbrutt meldekortbehandling. Støtte for at saksbehandler skal kunne avbryte behandlingen. 
Noen ting jeg var litt usikker på: 
1. Kan jeg anta at vi ikke har noen MeldekortUnderBehandling hvis saksbehandler ikke har opprettet den? 
2. Er det greit at saksbehandler avbryter behandling som enten er tildelt seg selv eller ikke tildelt? Eller bør vi krever at behandlingen er tildelt for å være sikker på at saksbehandler har opprettet den (ref punkt 1)? 
3. Jeg har lagt inn et krav om at vi ikke kan ha noen meldekort fra bruker når man avbryter behandlingen. Er det riktig? 
https://trello.com/c/XU9ti14p/1461-mulig-for-saksbehandler-%C3%A5-avslutte-manuell-meldekortbehandling

Avslutt meldekortbehandling

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandlinger.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortUnderBehandling.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/AvbrytMeldekortBehandlingRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/MeldeperiodeKjedeDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/UtbetalingsstatusDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/sak/Sak.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/Utbetalingsstatus.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/infra/repo/UtbetalingsstatusDbType.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/AvbrytMeldekortBehandlingRouteTest.kt

Avbrutte behandlinger skal ikke være en del av resten av meldekortbehandlingene og skal ikke påvirke videre behandling, så de må filtreres ut der vi bruker meldekortbehandlingene. De skal derimot vises i frontend, så vi må inkludere dem i responsen. 
https://trello.com/c/XU9ti14p/1461-mulig-for-saksbehandler-%C3%A5-avslutte-manuell-meldekortbehandling

Avslutt meldekortbehandling apifiks

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/OppdaterBegrunnelseVilkårsvurderingRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/SendBehandlingTilBeslutningRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/SendRevurderingTilBeslutningRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/barnetillegg/BarnetilleggDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/barnetillegg/OppdaterBarnetilleggRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/brev/ForhåndsvisVedtaksbrevRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/brev/OppdaterFritekstRoute.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/OppdaterMeldekortDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/dto/SendMeldekortTilBeslutterDTO.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/sak/infra/routes/AvbrytSøknadOgBehandlingRoute.kt

https://trello.com/c/zDmTAbXR/1409-fjerne-rare-tegn-fra-fritekstfelter
(jeg har droppet dette for de tekstene som kun brukes i kommunikasjon mellom saksbehandler og beslutter og som ikke er med i pdf-en, f.eks. begrunnelse for underkjenn)

1409 fjerner tegn som kan brekke pdf-generering fra input

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/Søknad.kt

https://trello.com/c/nZ9T9Wzl/1564-bug-feil-begrunnelse-n%C3%A5r-en-s%C3%B8knad-ikke-kan-behandles-delvis-automatisk

1564 retter sjekk av om søknad er sendt for sent

---

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/datadeling/infra/client/DatadelingVedtakJson.kt
src/main/kotlin/no/nav/tiltakspenger/saksbehandling/vedtak/infra/repo/RammevedtakPostgresRepo.kt
src/test/kotlin/no/nav/tiltakspenger/saksbehandling/vedtak/infra/repo/RammevedtakPostgresRepoTest.kt

Denne vil medføre at vi deler alle avslagsvedtak med tiltakspenger-datadeling når den deployes. For å få oppdatert tiltakspenger-datadeling med stansgrunner må stans-vedtakene resendes (det tenkte jeg å gjøre manuelt siden det ikke er så mange). 
https://trello.com/c/A9xGZY5O/1412-nks-salesforce-trenger-data-om-tiltakspengevedtak-og-meldekort

1412 deler avslagsvedtak, stans/avslagsgrunner og oppdaterer format
