domene/src/main/kotlin/no/nav/tiltakspenger/vedtak/Søker.kt, domene/src/main/kotlin/no/nav/tiltakspenger/vedtak/Tiltaksaktivitet.kt, domene/src/main/kotlin/no/nav/tiltakspenger/vedtak/Ytelsesak.kt
Trenger vi alle feltene? De er nå kopiert rått fra fakta-innhenterne..
=> Lagt til klasser for ytelser, tiltak og egenAnsatt

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/SøkerRepository.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/søker/InMemorySøkerRepository.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/søker/PostgresSøkerRepository.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/søknad/PostgresSøknadDAO.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/søknad/SøknadDAO.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/repository/søker/PostgresSøkerRepositoryTest.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/repository/søknad/PostgresSøknadDAOTest.kt
_Skriv 1 eller 2 setninger om hvilken funksjonell endring som blir implementert._
_Er det noe du er bekymret eller usikker på? Beskriv det gjerne her._
_Har du husket alle punktene i listen?_
_Jeg har ikke skrevet tester fordi:_
_F.eks. commit for commit, alt i ett?_
=> Temp branch1

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/søker/SøkerRoutes.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/søker/BehandlingMapper.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/søker/SøkerService.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/søker/SøkerServiceImpl.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/routes/søker/InnsendingRoutesTest.kt, domene/src/main/kotlin/no/nav/tiltakspenger/vedtak/Innsending.kt
Kunne noe sånt som dette vært en måte vi kunne sjekket for endringer på? At frontend kaller `/innsending/hash` med jevne mellomrom og differ hash-verdien opp mot den som kom med innsendingen?
Det er sikkert en rekke måter å gjøre dette på, så alle andre forslag mottas med takk! :)
=> Lagt til et forslag til endepunkt for å sjekke om innsending er endret

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTO.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/saksopplysning/Saksopplysning.kt
…nuell)
B Hvis saksbehandler retter noe som krever manuell, skal den ikke kreve manuell lengre
=> B Sett korrekt utfall for kategori (Ikke Oppfylt overstyrer krever manuell)

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/ApplicationBuilder.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/vedtak/VedtakServiceImpl.kt
Lager dto for meldekort grunnlag og sender det til vedtak rivers via kafka
=> F - Sender meldekort grunnlag til meldekort-api

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/vedtak/BrevDTO.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/vedtak/MeldekortGrunnlagDTO.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/vedtak/VedtakServiceImpl.kt
Sender vedtaksbrev til dokument via kafka
=> F La til brevDTO og sender den til dokument

domene/src/main/kotlin/no/nav/tiltakspenger/felles/Ulid.kt
R Skrive sammenlikning av ulid-ider mer leselig ved å bruke toString sin innebygde compareTo-metode.
Har bare skrevet om metoden som beskrevet i commit-meldinga
Ingen ekstra info
=> R Skrive sammenlikning av ulid-ider mer leselig ved å bruke toString sin innebygde compareTo-metode.

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTO.kt
Sender med samletUtfall til frontend så det slipper å utledes der
Ingen kommentar 🔕
=> F Send med samletUtfall på valgt behandling

domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/Behandling.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/BehandlingIverksatt.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/BehandlingTilBeslutter.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/BehandlingVilkårsvurdert.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/Søknad.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/behandling/Søknadsbehandling.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/personopplysninger/SakPersonopplysninger.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/saksopplysning/Kilde.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/saksopplysning/Saksopplysning.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/saksopplysning/Saksopplysninger.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/saksopplysning/TypeSaksopplysning.kt, domene/src/main/kotlin/no/nav/tiltakspenger/domene/vilkår/Vilkår.kt
Jeg har ryddet litt i koden rundt Saksbehandling, som var strødd litt rundt omkring. På generell basis bærer koden preg av å være "procedural", jeg savner litt OOP. Og de ulike prosedyrene er ikke samlet på ett logisk sted, men spredd rundt der de tilfeldigvis brukes. 
Aller helst vil jeg lage en klasse Saksopplysninger, på samme måte som jeg gjorde med SakPersonopplysninger, men iom at jeg ikke har fått godkjent den PRen ennå så tar jeg det litt roligere i svingene her. Så her er bare de ulike fun-ene samlet i et objekt.
=> Jeg har ryddet litt i koden rundt Saksbehandling

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/service/behandling/BehandlingServiceImpl.kt
Vi gjorde mer eller mindre det samme mange steder, så jeg lagde en hjelpemetode. Litt usikker på om dette trengte å være en PR...?
=> Refaktorert litt, trukket ut en hjelpemetode

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTO.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/SammenstillingForBehandlingDTOTest.kt
Fikser en byggefeil som følge av merge av en PR
Ingen kommentarer
=> B Fikser ødelagt bygg

README.md
Forslag til readme som forklarer hvordan man kjører opp appen lokalt
Ingen kommentarer. Men tar veldig gjerne kommentarer fra dere 😁 Noe mer vi bør ha med?
=> D Lagt inn info om lokal kjøring i README

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/sak/PostgresSakRepo.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/VedtakApi.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/sak/SakDTO.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/sak/SakRoutes.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/ports/SakRepo.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/sak/SakService.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/sak/SakServiceImpl.kt
Lagt til routes for å hente ut detaljer om Sak. Det er lagt til én route for å hente ut Sak basert på saksnummer, og en annen for å hente ut alle Sak som tilhører en søkerId. 
Ingen kommentarer.
=> F Lagt til routes for å hente ut detaljer om Sak

app/src/test/kotlin/no/nav/tiltakspenger/vedtak/repository/sak/SakRepoTest.kt
* Test av hentForSaksnummer
* Test av hentForIdent
Se tittel
Ingen kommentarer
=> La til to tester i SakRepoTest

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/BehandlingRoutes.kt
Midlertidig fiks som gjør det mulig å opprette revurderinger utifra Saksnummer
Usikker på om vi trenger å merge dette egentlig... Ta det hvis det blir behov? Det kommer til å endres på etter påsken uansett. @sneha-d-desai @KarlEvaldNav
=> F Opprette revurdering fra Saksnummer

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/behandling/PostgresBehandlingRepo.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/Behandling.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/Førstegangsbehandling.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/Revurderingsbehandling.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/vilkår/Vilkårssett.kt, domene/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/RevurderingOpprettetTest.kt
=> Samle saksopplysninger og vurderinger i vilkårssett

.nais/vars/dev.yml, .nais/vars/prod.yml, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/Configuration.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/felles/SaksbehandlerDbJson.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/VedtakApi.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/dto/SaksbehandlerDTO.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/BehandlingBeslutterRoutesTest.kt, domene/src/main/kotlin/no/nav/tiltakspenger/felles/Rolle.kt, domene/src/main/kotlin/no/nav/tiltakspenger/felles/Saksbehandler.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/behandling/Førstegangsbehandling.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/service/behandling/BehandlingServiceImpl.kt, test-common/src/main/kotlin/no/nav/tiltakspenger/objectmothers/SaksbehandlerMother.kt
Fjerner rollen administrator og bruken av den
=> F - Fjern Administrator rolle

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/person/HentPersonQuery.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/clients/person/PdlResponseManglendeIdentPåBarn.kt
Fjern Kjoenn fra pdl query da den ikke er i bruk
=> F - Fjern Kjoenn fra pdl query

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/meldekort/MeldekortdagDbJson.kt, domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/domene/Meldeperiode.kt
=> F - Lagre Sperretdager i databasen

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/pdfgen/DokumentMeldekortDTO.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/pdfgen/PdfgenHttpClient.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/context/ApplicationContext.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/context/UtbetalingContext.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/clients/pdfgen/PdfgenHttpClientTest.kt, domene/src/main/kotlin/no/nav/tiltakspenger/meldekort/ports/GenererMeldekortPdfGateway.kt, domene/src/main/kotlin/no/nav/tiltakspenger/utbetaling/service/JournalførUtbetalingsvedtakService.kt, test-common/src/main/kotlin/no/nav/tiltakspenger/common/TestApplicationContext.kt, test-common/src/main/kotlin/no/nav/tiltakspenger/fakes/clients/GenererFakeMeldekortPdfGateway.kt
Fjerner felter om brukers navn.
Legger til felter for saksbehandlers (og beslutters) navn.
Beslutter sitt navn er nullable, men legger inn en sjekk som krever at det har en verdi før vi gjør kallet mot Microsoft Graph Api med en beskrivende feilmelding.
=> F - Oppdater dataen vi journalfører for meldekort

.nais/nais.yml, .nais/vars/dev.yml, .nais/vars/prod.yml, app/build.gradle.kts, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/App.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/Configuration.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/context/ApplicationContext.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/arena/TiltaksdeltakerArenaConsumer.kt, domene/build.gradle.kts, test-common/build.gradle.kts
Skal bygge videre på lytteren i en senere pr, dette er mest for å se at selve oppsettet virker siden appen ikke har brukt kafka før, og siden oppsettet i libs også er nytt. 
https://trello.com/c/xwqA0nvR/1313-saksbehandler-m%C3%A5-f%C3%A5-vite-om-relevante-endringer-i-tiltaksdeltakelsen
=> setter opp kafkalytter

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/App.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/Configuration.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/context/ApplicationContext.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/TiltaksdeltakerService.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/komet/DeltakerV1Dto.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/komet/TiltaksdeltakerKometConsumer.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/TiltaksdeltakerServiceTest.kt
Lagrer de komet-deltakerne som er relevante for oss, ref https://trello.com/c/xwqA0nvR/1313-saksbehandler-m%C3%A5-f%C3%A5-vite-om-relevante-endringer-i-tiltaksdeltakelsen
=> lagrer relevante deltakere fra komet-topic

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/App.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/jobber/TaskExecutor.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/HealthRoutes.kt
Lar appen slå seg av kontrollert så den blir ferdig med det den holder på med. Ønsker heller ikke å kjøre jobber hvis appen er på vei til å slå seg av. 
Det som gjelder jobbene kan sikkert flyttes til libs når vi ser at det virker :)
=> Shutdownhook

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/App.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/clients/oppgave/OppgaveHttpClient.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/arena/ArenaDeltakerMapper.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/jobb/EndretTiltaksdeltakerJobb.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/komet/DeltakerV1Dto.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/komet/TiltaksdeltakerKometConsumer.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/repository/TiltaksdeltakerKafkaDb.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/repository/TiltaksdeltakerKafkaRepository.kt, app/src/main/resources/db/migration/V35__tiltaksdeltakerkafka_add_oppgave_sist_sjekket.sql, app/src/test/kotlin/no/nav/tiltakspenger/tiltaksdeltakelser/TiltaksdeltakerServiceTest.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/jobb/EndretTiltaksdeltakerJobbTest.kt, app/src/test/kotlin/no/nav/tiltakspenger/vedtak/kafka/tiltaksdeltakelser/repository/TiltaksdeltakerKafkaDbTest.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/ports/OppgaveGateway.kt, test-common/src/main/kotlin/no/nav/tiltakspenger/fakes/clients/OppgaveFakeGateway.kt
Vi sjekker jevnlig (hver time) om oppgaven vi har opprettet er ferdigstilt. Hvis den er det sletter vi innslaget i arbeidstabellen. 
Del av https://trello.com/c/xwqA0nvR/1313-saksbehandler-m%C3%A5-f%C3%A5-vite-om-relevante-endringer-i-tiltaksdeltakelsen.
=> jobb for å rydde opp hvis oppgaven er ferdigstilt

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/behandling/dto/SaksopplysningerDTO.kt
SaksopplysningerDTO kan inneholde en liste med tiltak: https://trello.com/c/W9ifbenn/1315-st%C3%B8tte-at-vi-f%C3%A5r-flere-tiltak-fra-arena-komet-n%C3%A5r-vi-s%C3%B8ker-opp-et-fnr
Pga endringen her https://github.com/navikt/tiltakspenger-saksbehandling/commit/327f4d8578ebcb61995649837c10fdee68b215f6 bør dette går fint 🙏
=> saksopplysningerdto kan inneholde en liste med tiltaksdeltakelser

.nais/nais.yml
https://doc.nais.io/persistence/postgres/how-to/enable-auditing/
=> Legger til konfigurasjon for pgaudit i nais.yml

app/src/main/kotlin/no/nav/tiltakspenger/vedtak/repository/statistikk/stønad/StatistikkStønadPostgresRepo.kt, app/src/main/kotlin/no/nav/tiltakspenger/vedtak/routes/meldekort/dto/MeldeperiodeKjedeDTO.kt, domene/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/domene/vedtak/Vedtaksliste.kt
Responsen må inneholde en liste med tiltakstyper. Bruker funksjon for overlapp fra libs. 
https://trello.com/c/W9ifbenn/1315-st%C3%B8tte-at-vi-f%C3%A5r-flere-tiltak-fra-arena-komet-n%C3%A5r-vi-s%C3%B8ker-opp-et-fnr
=> Tiltaksnavn-liste

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/routes/behandling/dto/SøknadDTO.kt
Brukes i frontend for å bestemme hvorvidt bolken om vedlegg skal vises eller ikke
=> 1331 Bare vis vedlegg dersom det er lagt inn barn manuelt i søknaden

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/saksbehandling/domene/behandling/Behandling.kt, app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/saksbehandling/domene/tiltak/ValgteTiltaksdeltakelser.kt, app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/routes/behandling/tilbeslutter/SendFørstegangsbehandlingTilBeslutningBuilder.kt, app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/routes/behandling/tilbeslutter/SendFørstegangsbehandlingTilBeslutterTest.kt
Skal ikke kunne velge tiltaksdeltakelser utenfor deltakelsens periode, og virkningsperioden må stemme overens med valgte perioder for tiltaksdeltakelse. 
https://trello.com/c/iwTGibtq/1376-saksbehandler-skal-ikke-kunne-innvilge-tiltakspenger-for-dager-man-ikke-deltar-p%C3%A5-tiltak
=> Validering

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/datadeling/infra/client/DatadelingVedtakJson.kt
Hvis det innvilges barnetillegg må det deles som en del av vedtaket med tiltakspenger-datadeling. 
https://trello.com/c/fXQ3FHT4/1202-fikse-integrasjon-mellom-datadeling-og-modia
=> 1202 deler barnetillegg som en del av vedtak

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/routes/exceptionhandling/ExceptionHandler.kt
Glemte det mest åpenbare stedet å endre dette 😅
=> logger exceptions i vanlig logg

app/src/main/kotlin/no/nav/tiltakspenger/saksbehandling/saksbehandling/domene/behandling/SakBehandlingEx.kt, app/src/test/kotlin/no/nav/tiltakspenger/saksbehandling/routes/behandling/tilbeslutter/SendRevurderingTilBeslutningTest.kt
Skal ikke kunne sette stansdato til etter at innvilgelsesperioden er avsluttet. 
https://trello.com/c/qQybvC8d/1395-bug-n%C3%A5-er-det-mulig-%C3%A5-stanse-allerede-stanset-periode
=> 1395 skal ikke kunne stanse etter siste dag med tiltakspenger

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/dokument/infra/BrevRevurderingStansDTO.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/dokument/infra/BrevSøknadInnvilgetDTO.kt
Må sjekke om det er greit at jeg merger denne
https://trello.com/c/2ozdWCzt/1413-hardkode-nasjonal-enhet-som-signatur-i-brev
=> 1413 Hardkoder "Nav Tiltakspenger" som kontor for signatur i brev

build.gradle.kts, src/main/avro/Personhendelse.avdl, src/main/avro/leesah/Doedsfall.avdl, src/main/avro/leesah/ForelderBarnRelasjon.avdl, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/App.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/setup/BehandlingOgVedtakContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/brev/ForhåndsvisVedtaksbrevService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/journalføring/JournalførRammevedtakService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/route/Routes.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/Configuration.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/infra/kafka/LeesahConsumer.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/infra/setup/PersonContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/saksbehandler/NavIdentClient.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/saksbehandler/infra/MicrosoftGraphApiClient.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/saksbehandler/route/MeRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/infra/setup/UtbetalingContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/service/JournalførUtbetalingsvedtakService.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/clients/person/FakeNavIdentClient.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/infra/routes/MeRouteTest.kt
Setter opp lytter for leesah-meldinger. 
I første omgang bruker jeg et plugin for kodegenerering som ikke lenger blir vedlikeholdt, pga mangel på andre alternativer. Det går an å hacke det til på andre måter, og det er mulig vi bør gjøre det senere, men i første omgang skal jeg bare se om det virker sånn ellers. 
Jeg flyttet forresten også ting som gjaldt saksbehandler ut av person-pakken. 
https://trello.com/c/gDaBF3Ps/1421-lytte-p%C3%A5-leesah-topic-og-opprette-oppgave-i-gosys-hvis-bruker-som-mottar-tiltakspenger-d%C3%B8r-eller-f%C3%A5r-barn
=> Leeashlytter

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/App.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/OppgaveGateway.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/oppgave/infra/OppgaveDto.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/oppgave/infra/OppgaveHttpClient.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/PersonhendelseService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/jobb/PersonhendelseJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/repo/PersonhendelseRepository.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/vedtak/Vedtaksliste.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/PersonhendelseServiceTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/jobb/PersonhendelseJobbTest.kt
Oppretter oppgave hvis bruker mottar tiltakspenger nå eller hvis det er fattet positivt vedtak frem i tid. 
Endret også litt på sjekken slik at vi ignorerer hendelser der vår bruker får foreldre (hvis det kan skje 😅)
https://trello.com/c/gDaBF3Ps/1421-lytte-p%C3%A5-leesah-topic-og-opprette-oppgave-i-gosys-hvis-bruker-som-mottar-tiltakspenger-d%C3%B8r-eller-f%C3%A5r-barn
=> Personhendelse opprett oppgave

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/App.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/jobb/PersonhendelseJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/repo/PersonhendelseRepository.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/jobb/PersonhendelseJobbTest.kt
https://trello.com/c/gDaBF3Ps/1421-lytte-p%C3%A5-leesah-topic-og-opprette-oppgave-i-gosys-hvis-bruker-som-mottar-tiltakspenger-d%C3%B8r-eller-f%C3%A5r-barn
=> 1421 sletter personhendelse hvis oppgaven er ferdigstilt

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/PersonhendelseService.kt
Noen ganger kan alle feltene mangle, typisk ved annullering. Tenker at vi kan se bort fra dem inntil videre.
=> hvis alle felter mangler ser vi bort fra meldingen

src/main/avro/Personhendelse.avdl, src/main/avro/leesah/Adressebeskyttelse.avdl, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/StatistikkSakRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/PersonhendelseService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/jobb/PersonhendelseJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/kafka/LeesahConsumer.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/kafka/Opplysningstype.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/infra/repo/sak/StatistikkSakRepoImpl.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/fakes/repos/StatistikkSakFakeRepo.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/PersonhendelseServiceTest.kt
Hvis vi får melding om adressebeskyttelse så må vi sjekke med PDL hva som er riktig gradering. Hvis bruker har fått kode 6 skal vi oppdatere statistikk-tabellen slik at vi ikke deler den gamle informasjonen her mer til DVH. 
https://trello.com/c/zwDnNL3h/1427-lytte-p%C3%A5-endringer-i-adressebeskyttelse-og-oppdatere-hvis-bruker-f%C3%A5r-adressebeskyttelse
=> Adressebeskyttelse

build.gradle.kts, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/StartBehandlingRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/iverksett/IverksettBehandlingRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/metrikker/MetricRegister.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/KtorSetup.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/infra/route/MottaSøknadRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/service/OppdaterUtbetalingsstatusService.kt
La inn noen metrikker som jeg tenkte kan være kjekke å ha :)
https://trello.com/c/R6tSX10l/1344-saksbehandling-api-deler-ikke-metrikker
=> 1344 saksbehandling-api må dele metrikker

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/setup/MeldekortContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/IverksettMeldekortService.kt
https://trello.com/c/BO0hy6F7/1457-gosys-oppgaven-som-opprettes-n%C3%A5r-meldekort-er-mottatt-fra-bruker-ferdigstilles-automatisk-n%C3%A5r-saksbehandler-har-beslutter-har-go
=> 1457 ferdigstiller oppgave for meldekort ved iverksetting

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/KanIkkeIverksetteMeldekort.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/KunneIkkeUnderkjenneMeldekortBehandling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletManuelt.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/IverksettMeldekortRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/OppdaterMeldekortBehandlingRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/SendMeldekortTilBeslutterRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/UnderkjennMeldekortBehandlingRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/IverksettMeldekortService.kt
https://trello.com/c/iYXkiirR/1458-en-p%C3%A5startet-manuell-meldekortbehandling-m%C3%A5-kunne-overtas-av-en-annen-saksbehandler
=> 1458 bedre tekster for feilmeldinger

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortBehandletManuelt.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortUnderBehandling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/OvertaMeldekortBehandlingRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/overta/KunneIkkeOvertaMeldekortBehandling.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/domene/personopplysninger/BehandlingTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/OvertaMeldekortBehandlingRouteTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/SaksbehandlerMother.kt
Ref feil oppdaget under testing av https://trello.com/c/iYXkiirR/1458-en-p%C3%A5startet-manuell-meldekortbehandling-m%C3%A5-kunne-overtas-av-en-annen-saksbehandler
=> skal ikke få overta behandling som beslutter uten beslutterrolle

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/Meldeperiode.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldeperiodeKjeder.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldeperiodePostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/RammevedtakMeldeperiodeDbJson.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/vedtak/Vedtaksliste.kt, src/main/resources/db/migration/V79__meldeperiode_add_rammevedtak.sql, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/MeldeperiodePostgresRepoTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/MeldekortMother.kt
Vi trenger å vite hvilke rammevedtak som er bakgrunnen for dagene i en meldeperiode. 
https://trello.com/c/QrEX50Cm/1476-legge-til-relaterte-vedtak-p%C3%A5-meldeperiode
=> 1476 legger til relaterte rammevedtak på meldeperioden

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/setup/AvbrytSøknadOgBehandlingContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/setup/BehandlingOgVedtakContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/avslutt/AvbrytSøknadOgBehandlingServiceImpl.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/LeggTilbakeBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/SendBehandlingTilBeslutningService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/TaBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/overta/OvertaBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/sak/StartRevurderingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakMapper.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakService.kt
https://trello.com/c/F5apn3yE/1481-hvis-en-behandling-avsluttes-skal-det-deles-med-dvh
=> 1481 deler at behandling avbrytes med DVH

build.gradle.kts, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/App.kt
https://trello.com/c/j9Ozj5P1/1406-tidvis-exception-fra-jobbene-n%C3%A5r-vi-stanser-applikasjonen
=> 1406 sender inn attributes for å unngå feil hvis appen er stoppet

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/dokument/infra/PdfgenHttpClient.kt
https://trello.com/c/5nleiYmo/1402-bedre-feilmelding-n%C3%A5r-forh%C3%A5ndsvisning-av-brev-feiler
=> 1402 øker timeout mot pdfgen

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/infra/route/SøknadDTO.kt
https://trello.com/c/9CHcCuws/1540-bug-barn-oppholder-seg-innenfor-norge-e%C3%B8s-svarer-nei-i-s%C3%B8knaden-vises-som-ja-i-saksbehandlerflaten
=> frontend forventer boolean og ikke ja/nei

build.gradle.kts, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/domene/Behandling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/domene/BehandlingResultat.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/domene/Behandlingsstatus.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/repo/BehandlingsstatusDb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/OvertaBehandlingRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/dto/BehandlingsstatusDTO.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/LeggTilbakeBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/TaBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/brev/ForhåndsvisVedtaksbrevService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/overta/KunneIkkeOvertaBehandling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/overta/OvertaBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/datadeling/infra/client/DatadelingBehandlingJson.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/repo/BenkOversiktFakeRepo.kt
https://trello.com/c/AuS17sfh/1509-delvis-automatisk-behandling-med-manuell-beslutning-for-enkle-innvilgelsessaker
=> 1509 legger til ny behandlingstatus

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/SakRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/StatistikkSakRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/StatistikkStønadRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/SøknadRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/jobb/IdenthendelseJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/sak/infra/repo/SakPostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakPostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkStønadPostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkUtbetalingDTO.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/infra/repo/SøknadPostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/Utbetalingsvedtak.kt, src/main/resources/db/migration/V103__statistikk_utbetaling_add_bruker_id.sql, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/jobb/IdenthendelseJobbTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/sak/infra/repo/SakFakeRepo.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakFakeRepo.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkStønadFakeRepo.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/søknad/infra/repo/SøknadFakeRepo.kt
Har også endret slik at vi bruker transaksjon for oppdatering av fnr. 
https://trello.com/c/oMeA1pOQ/1547-legge-til-brukerid-i-statistikkutbetaling-tabellen
=> 1547 legger til bruker_id i utbetalingtabell for dvh

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/ports/OppgaveKlient.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/oppgave/infra/OppgaveDto.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/oppgave/infra/OppgaveHttpClient.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/tiltaksdeltagelse/infra/kafka/jobb/EndretTiltaksdeltakerJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/tiltaksdeltagelse/infra/kafka/jobb/TiltaksdeltakerEndring.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/tiltaksdeltagelse/infra/kafka/repository/TiltaksdeltakerKafkaDb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/tiltaksdeltagelse/infra/kafka/repository/TiltaksdeltakerKafkaRepository.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/oppgave/infra/OppgaveFakeKlient.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/tiltaksdeltagelse/infra/kafka/TiltaksdeltakerServiceTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/tiltaksdeltagelse/infra/kafka/jobb/EndretTiltaksdeltakerJobbTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/tiltaksdeltagelse/infra/kafka/repository/TiltaksdeltakerKafkaDbTest.kt
https://trello.com/c/x2Cseudt/1536-ser-ikke-hva-som-er-endringen-n%C3%A5r-tiltaket-har-endret-seg-med-periode-og-eller-status-i-gosys
=> Oppgavebeskrivelse endret deltakelse

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/benk/domene/BehandlingssammendragBenktype.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/benk/domene/HentÅpneBehandlingerCommand.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/benk/infra/repo/BenkOversiktPostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/benk/infra/routes/HentBenkRoute.kt, src/main/resources/db/migration/V108__behandling_index_ersattpaavent.sql, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/benk/infra/repo/BenkOversiktPostgresRepoTest.kt
https://trello.com/c/D1dGCGcv/1552-saksbehandler-og-beslutter-skal-kunne-sette-en-behandling-p%C3%A5-vent
=> 1552 La saksbehandler filtrere på hvorvidt behandlingene er satt på vent eller ei

.nais/nais.yml, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/IkkeTilgangDetaljer.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/TilgangskontrollService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/infra/AvvistTilgangResponse.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/infra/PersonRequestItem.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/infra/TilgangBulkResponse.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/infra/TilgangsmaskinClient.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/infra/TilgangsmaskinHttpClient.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/Configuration.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/auth/tilgangskontroll/TilgangskontrollServiceTest.kt
Lager klar klient, service og integrasjonsbiten, og så tar jeg det i bruk i neste runde. Blir ikke merget før i morgen tidlig. 
https://trello.com/c/6nihAwZ9/1487-bytt-til-tilgangsmaskinen
=> 1487 legger til integrasjon mot tilgangsmaskinen

src/main/resources/db/migration/V118__utbetalingvedtak_neste_forsok.sql
https://trello.com/c/pQ9wp5dT/1569-utbetalinger-som-feiler-mot-helved-trenger-en-backoff-strategi
=> 1569 Script for å legge til nesteForsøk i status_metadata

.nais/nais.yml, .nais/vars/dev.yml, .nais/vars/prod.yml, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/BehandleSøknadPåNyttService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/IverksettBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/StartSøknadsbehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/Configuration.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/infra/setup/PersonContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/StatistikkContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/behandling/StatistikkSakService.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/LocalApplicationContext.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/common/TestApplicationContext.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/infra/http/FellesFakeAdressebeskyttelseKlient.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/infra/http/FellesFakeSkjermingsklient.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/infra/http/TilgangsstyringFakeKlient.kt
This reverts commit ff815d93132662e8d672b33472ab0f34c79ca06b.
Vi kan heller fjerne poao-tilgang.
=> Revert "1487 rydder bort ubrukte klienter (#1138)"

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/infra/setup/ApplicationContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/setup/MeldekortContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/AutomatiskMeldekortBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/IverksettMeldekortService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/jobb/IdenthendelseJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/person/personhendelser/jobb/PersonhendelseJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/StatistikkContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/meldekort/StatistikkMeldekortDTO.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/meldekort/StatistikkMeldekortPostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/meldekort/StatistikkMeldekortRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkStønadPostgresRepo.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkUtbetalingDTO.kt, src/main/resources/db/migration/V125__statistikk_utbetaling_add_meldeperioder.sql, src/main/resources/db/migration/V126__create_table_statistikk_meldekort.sql, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/LocalApplicationContext.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/common/TestApplicationContext.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/infra/repo/TestDataHelper.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/person/identhendelser/jobb/IdenthendelseJobbTest.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/meldekort/StatistikkMeldekortFakeRepo.kt
https://trello.com/c/z1SYbRDy/1416-dele-data-om-meldekort-med-dvh
=> Dvh meldekort

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/App.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/StatistikkContext.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/jobb/OpprettStatistikkJobb.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/statistikk/vedtak/StatistikkUtbetalingDTO.kt
Starter med en jobb som legger til meldeperioder for de statistikk-utbetaling-innslagene som mangler det. I neste omgang lager vi meldekort-statistikk. 
https://trello.com/c/z1SYbRDy/1416-dele-data-om-meldekort-med-dvh
=> Meldekortstatistikk jobb

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/domene/søknadsbehandling/KanIkkeSendeTilBeslutter.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/SendBehandlingTilBeslutningRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/IverksettBehandlingService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/service/behandling/SendBehandlingTilBeslutningService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/OppsummeringGenerator.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/Simulering.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/ValiderKanIverksetteUtbetaling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/infra/repo/SimuleringEndringDbJson.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/SimuleringMother.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/UtbetalingerIT.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/OppsummeringGeneratorTest.kt
- Kan ikke sende behandling til beslutning dersom den har en utbetaling med negativt beløp (feilutbetaling eller justering).
- Tillater igjen behandling med utbetaling med kun positive beløp
=> Ikke tillat negativ utbetaling

src/main/kotlin/no/nav/tiltakspenger/saksbehandling/behandling/infra/route/SendBehandlingTilBeslutningRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/KanIkkeSendeMeldekortTilBeslutter.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/MeldekortUnderBehandling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/domene/SendMeldekortTilBeslutterKommando.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/infra/route/SendMeldekortTilBeslutterRoute.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/meldekort/service/SendMeldekortTilBeslutterService.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/OppsummeringGenerator.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/Simulering.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/ValiderKanIverksetteUtbetaling.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/infra/repo/SimuleringEndringDbJson.kt, src/main/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/infra/routes/KanIkkeIverksetteUtbetalingResponse.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/infra/repo/TestDataHelperMeldekortEx.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/objectmothers/SimuleringMother.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/UtbetalingerIT.kt, src/test/kotlin/no/nav/tiltakspenger/saksbehandling/utbetaling/domene/OppsummeringGeneratorTest.kt
Innfører samme restriksjoner som for utbetaling på rammebehandling
=> Må ha simulering og kan ikke ha feilutbetaling for å sende meldekortbehandling til beslutning
